### PR TITLE
Re-add centering

### PR DESCRIPTION
**Pull request by fsih**
Put back center snapping

This adds a fix for the crash, the repro steps were:
Switch to the costumes tab
File -> New
Switch to the costumes tab again

This also adds fading the crosshair when you're not dragging close to it, which I forgot to cherry-pick into the original centering PR, haha?

Demo is up at https://fsih.github.io/scratch-gui/centering/

### CODE REVIEW

**Comment by adroitwhiz** [comment]
I'm not very familiar with React, so forgive my ignorance--is there any mechanism within React that can ensure the `PaperCanvas` element, which calls `paper.setup` and initializes the `paper.project.view`, "mounts" before all the other components?

Since it seems that moving `importSVG` calls to `onMouseDown` handlers is error-prone, this may indicate that https://github.com/LLK/scratch-paint/issues/937 isn't actually solved.

**Comment by fsih** [comment]
@adroitwhiz the crash was caused by us calling paper's importSVG method, and then unmounting the paper-canvas component before the load callback could get called. That somehow leaves paper permanently in a broken state. We're getting around the issue here by avoiding calling importSVG at all, but we do call it in lots of other places, so you could probably hit this crash in other ways if you had really unlucky timing. We'll probably have to keep looking into it.

**Comment by adroitwhiz** [comment]
It looks like [the importSVG method is synchronous if passed an SVG string](https://github.com/paperjs/paper.js/blob/develop/src/svg/SvgImport.js#L724), so if you import SVGs as strings via webpack's `raw-loader`, it should cause less weirdness (currently, SVGs are loaded as data URIs, which seem to follow [this code path](https://github.com/paperjs/paper.js/blob/develop/src/svg/SvgImport.js#L706)). It does seem rather fragile, though--maybe an "always synchronous" API (`importSVGString`?) could be added to Scratch's paper.js fork?

**Review by paulkaplan — APPROVED** [review]
LGTM, no crash and the crosshairs look the way ~they used to!~ they did in the previous version of this PR

**Pull request merged**
