### PR TITLE
Finish GUI-830: Add "coming soon" for bitmap, text tool

### PR DESCRIPTION
**Pull request by mewtaylor**
This brings over the "coming soon" tooltip created in gui as part of https://github.com/LLK/scratch-gui/pull/1069, and applies it to the text tool, as well as the "Convert to Bitmap" button. This finishes the implementation of https://github.com/LLK/scratch-gui/issues/830. /cc @carljbowman @thisandagain 

**Mac OSX 10.12, Chrome 63, 90% Screen zoom:**
screen shot 2017-12-21 at 11 27 24 am

**Mac OSX 10.12, Chrome 63, 100% Screen zoom:**
screen shot 2017-12-21 at 11 27 35 am

### CODE REVIEW

**Comment by thisandagain** [comment]
This is great. Thanks @mewtaylor! Looks like you have one failing lint issue:
```
/home/travis/build/LLK/scratch-paint/src/components/text-mode/text-mode.jsx
  22:13  error  JSX props should not use functions  react/jsx-no-bind
```

**Comment by mewtaylor** [comment]
Thanks @thisandagain ! dunno why it wasn't showing up in local tests, odd.

**Review by paulkaplan — DISMISSED** [review]
Code LG, tested locally working well. 

@carljbowman I didn't see this button in the mocks on invision, so just wanted to confirm the design. 
image

**Comment by carljbowman** [comment]
@paulkaplan - Yeah that button is suppose to be there. I will have a "coming soon" tooltip. Thanks for checking.

**Comment by fsih** [comment]
I noticed that the responsive sizing waits until it overlaps the 'more' button more before changing:
responsive

**Review by fsih — APPROVED** [review]

**Pull request merged**
