### PR TITLE
Bitmap select tool

### PR DESCRIPTION
**Pull request by fsih**
Adds bitmap select tool

select

### CODE REVIEW

**Comment by paulkaplan** [comment]
It looks like copy/paste causes a crashing error when used between bitmap and vector. Repro:
- Starting in vector, select the whole costume and hit "copy"
- Convert the costume to bitmap, hit "paste"
- All seems ok, there is a duplicate that is selected, you can move it around.
- Clicking outside doesn't seem to commit the vector to bitmap, leaves the vector object which is still selectable in the bitmap select tool
- Sometimes if you have that pasted object selected, choosing a different bitmap tools crashes the editor.

**Review by paulkaplan — CHANGES_REQUESTED** [review]
The code looks good overall. The only issue is that you can paste vector content into the bitmap editor (possibly vice-versa?) Once that is fixed then the rest looks good.

**Comment by fsih** [comment]
That paste issue should be fixed

**Comment by paulkaplan** [comment]
Looks good! I'm going to go ahead and merge this so that it is available for testing today.

**Review by paulkaplan — APPROVED** [review]

**Comment by fsih** [comment]
Yay, thank you Paul!!

**Pull request merged**
