### PR TITLE
Make stroke width 0 when transparent

### PR DESCRIPTION
**Pull request by fsih**
### Resolves
Fixes https://github.com/LLK/scratch-paint/issues/279

### Proposed Changes
When stroke color is transparent, make the width report 0
When stroke width is 0, make the color report transparent

When the stroke color is changed from transparent, make the width 1
When stroke width is changed from 0, make the color black

### Reason for Changes
Don't have hidden properties.
When you make changes, they are visible.

### CODE REVIEW

**Comment by benjiwheeler** [comment]
Code LGTM. Do you know why the checks are failing?

**Comment by fsih** [comment]
Ah, oops! I need to fix the tests

**Comment by fsih** [comment]
@benjiwheeler I got the stroke color to stay the same when you switch the width to 0 and then raise it up again, but it only works if you have something selected

**Comment by fsih** [comment]
Fixed tests

**Comment by benjiwheeler** [comment]
LGTM!

**Pull request merged**
