### PR TITLE
Show bounding box when moving and scaling in the select tool

### PR DESCRIPTION
**Pull request by fsih**
bounds

Fixes https://github.com/LLK/scratch-paint/issues/218

### CODE REVIEW

**Comment by paulkaplan** [comment]
@fsih would it be possible to update the positions of the bounds handles instead of removing them?

**Comment by fsih** [comment]
@paulkaplan I thought we agreed to just put in the box for now?

We actually used to show the handles when scaling, but it was really messy. We had to pass all of that UI from the bounding box tool to the scale and move tools for them to control, and I feel like the bounding box tool alone should be in charge of what the bounding box looks like ideally. Coming up with a good solution for this would take some time, and this bug is technically not in the Dec 20 iteration, so I wanted to put that off for now.
https://github.com/LLK/scratch-paint/commit/fd9a4af83f859565ed4c1e37993592c4f9bf2bb8#diff-e753d3454a0c89ede7c07efb1cc2b3b7L106

**Comment by paulkaplan** [comment]
@fsih ok i must have misunderstood. I thought we were going to move the handles and the box for everything except the rotation tool. LGTM

**Review by paulkaplan — APPROVED** [review]
LGTM

**Pull request merged**
